# Generated by Django 3.0.4 on 2020-04-17 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200417_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posting',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 9, 55, 1, 903393)),
        ),
    ]
